### ISSUE TITLE
zippyshare changed somehow?

### ISSUE THREAD

**Issue by ns6000** [Cartmanishere/zippyshare-scraper#28]
Hey, since today i can't process zippy links, it's testing them before output and all are getting redirected to hell and outputting this error:

if count > 3:
    logging.error('{} redirected more than {} times'.format(link, count))
    return None

i've tried to increase count but no dice...

**Comment by Cartmanishere** [comment]
@ns6000 It feels like something has changed from Zippyshare side. I will take some time to debug this.

**Comment by Cartmanishere** [comment]
@ns6000 I have pushed out a fix for this. It is working for me. Please checkout the latest code from this repo and try on your end.

**Comment by ns6000** [comment]
it's working now, thank you!

**Comment by ns6000** [comment]
I'm not complaining, just FYI. I've got chance to put it through it's paces and it's not 100% successful, there are maybe 1 or 2 instances per 50 links where it's still unable to generate true download link. But it's some timeout issue I presume, because if you try it multiple times, it eventually works.

**Comment by Cartmanishere** [comment]
@ns6000 I am facing a similar issue as well. This will take some time to debug. Till then, you can try increasing the retry count (I had already increased it to 8, maybe 10-15 should give enough chances that the links are parsed).

**Comment by ns6000** [comment]
ok, thanks for the tip

**Comment by advith231** [comment]
> @ns6000 I am facing a similar issue as well. This will take some time to debug. Till then, you can try increasing the retry count (I had already increased it to 8, maybe 10-15 should give enough chances that the links are parsed).

see the source code  of jdownloader2 it works perfectly with all zippyshare files although its wrriten in java

**Comment by Cartmanishere** [comment]
@advith231 I haven't looked too deep but afaik jdownloader uses an actual browser instance in the java process to run the javascript code and generate the download link. 

We have discussed a similar approach for this project [here](https://github.com/Cartmanishere/zippyshare-scraper/issues/13). But that approach is not as fast the current approach where we don't run any JS but extract the link by matching the link generation logic. 

As long as this works, I will not move to a browser runtime approach.

**Comment by Cartmanishere** [comment]
@ns6000 I have taken a new approach for generating download links. In my testing, this has proven more robust than previous approach. Please give it a try by cloning the latest code. (Note: Install the dependencies).

**Comment by ns6000** [comment]
@Cartmanishere i've tried 20 files and all without problems, great job, thank you!
